### ISSUE TITLE
import com.sipios.springsearch.anotation.SearchSpec not resolvable

### ISSUE THREAD

**Issue by jovanica7** [sipios/spring-search#33]
Hi,

I have noticed that this is not anymore resolvable in my class. Can you help out?
Only import com.sipios.springsearch.anotation.*; is possible.

**Comment by luc-boussant** [comment]
Hello, since when have you had this issue ?
When using the annotation on my projects, I am doing the following : 
```{java}
import com.sipios.springsearch.anotation.SearchSpec;
```
I am closing this issue for now. If it is still happening on your project can you specify the version of annotation that you use, the OS, the Java/Kotlin version. 

Thank you in advance,

**Comment by jovanica7** [comment]
Not sure, I have noticed it recently. It says: Cannot resolve symbol 'SearchSpec'.
I have added this dependency
<dependency>
    <groupId>com.sipios</groupId>
    <artifactId>spring-search</artifactId>
    <version>0.2.0</version>
</dependency>
So I guess the version is Maven/Spring Boot.
